# Cross-compile changes by Thomas E. Hansen (CodingCellist) 2021-03-08

ROOT := $(patsubst %/,%, $(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
XLEN := 64
TOOLCHAIN_PREFIX := $(ROOT)/../../buildroot/output/host/bin/riscv$(XLEN)-buildroot-linux-gnu-

PLATFORM ?= fpga/ariane

ifeq ($(PLATFORM),"fpga/openpiton")
PL_TARGET := 0
else
PL_TARGET := 1
endif

CC := $(TOOLCHAIN_PREFIX)gcc
CFLAGS := -O2 -pthread -D_XOPEN_SOURCE=500 -D_POSIX_C_SOURCE=200112 -DTOPRINT=0 -DPL_TARGET=$(PL_TARGET) -I$(ROOT)/../include -std=c11 -g -fno-strict-aliasing
LDFLAGS := -lm

# BASEDIR needs to be set to the same directory as this Makefile
# BASEDIR := $(HOME)/Splash-3/codes
BASEDIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
MACROS := $(BASEDIR)/pthread_macros/pthread.m4.stougie
M4 := m4 -Ulen -Uindex

ifndef BASEDIR
$(error Please define the BASEDIR variable)
endif

x = *

$(TARGET): $(OBJS) $(EXTRADEPS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o $(TARGET)

%.h: %.h.in
	$(M4) $(MACROS) $< > $@

%.c: %.c.in
	$(M4) $(MACROS) $< > $@

%.o: %.c $(EXTRADEPS)
	$(CC) -c $(CFLAGS) $<
